#!/usr/bin/env bash
# Installs ngnix, listens on port 80, modifies the default web file, configures redirect_me
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/whalay permanent;/" /etc/nginx/sites-available/default
service nginx restart
