#!/usr/bin/env bash
# ut will resets the server to work port 80 on nginx by replacing sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
