#!/usr/bin/env bash
# setting up firewall (ufw)
sudo apt install ufw -y
sudo ufw disable && sudo ufw enable

# listening to port 22, 80, and 443 only on tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
