#!/usr/bin/env bash
# This script makes a nginx server to run as the nginx user and listen on port 8080
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-enabled/default
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/lib/nginx
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx restart
